version: '3.8'

services:
  mcp-rally-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RALLY_API_KEY=${RALLY_API_KEY}
      - RALLY_WORKSPACE=${RALLY_WORKSPACE}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./.env:/app/.env:ro
